import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {lazy,Suspense,useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Moon,Sun,Pause,Play,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {applyTheme,readTheme} from './theme';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import SceneBoundary from './scene-boundary';
const StationScene=lazy(()=>import('./scene'));
import {visibilityFor} from './visibility';
import {restoreView,viewHash} from './view-url';
import {DAY_MS,TIMELINE_END,advanceAssembly,latestArrival,timelineStart,partLaunchTimes} from './assembly';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,SOURCES,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const PRESETS:{name:string;systems:SystemId[]}[]=[{name:'Modules only',systems:['us-modules','partner-modules','russian-modules']},{name:'Truss and power',systems:['truss','solar','thermal']}];
const SUGGESTED=['jem','ssrms','columbus','lab','sm','cupola','port-truss','starboard-truss'];
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0,assembly:null};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [theme,setTheme]=useState(readTheme);
 useEffect(()=>applyTheme(theme),[theme]);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 const [shareMessage,setShareMessage]=useState(''),[shareFallback,setShareFallback]=useState('');
 const [playing,setPlaying]=useState(false),assemblyRef=useRef(state.assembly);assemblyRef.current=state.assembly;
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The station catalogue could not be loaded.');return r.json();}).then((data:Atlas)=>{const restored=restoreView(location.hash,data,initial,timelineStart(data),TIMELINE_END);setState(restored.state);setChosen(restored.chosen);setDetails(!!restored.chosen);setAtlas(data);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{if(!atlas)return;const timer=setTimeout(()=>history.replaceState(null,'',location.pathname+location.search+viewHash(state,atlas)),250);return()=>clearTimeout(timer);},[atlas,state]);
 useEffect(()=>{if(!atlas)return;const restore=()=>{const restored=restoreView(location.hash,atlas,initial,timelineStart(atlas),TIMELINE_END);setPlaying(false);setState(s=>({...restored.state,reset:s.reset+1}));setChosen(restored.chosen);setDetails(!!restored.chosen);};window.addEventListener('hashchange',restore);return()=>window.removeEventListener('hashchange',restore);},[atlas]);
 const share=async()=>{if(!atlas)return;const url=location.origin+location.pathname+location.search+viewHash(state,atlas);try{await navigator.clipboard.writeText(url);setShareMessage('View link copied');setShareFallback('');}catch{setShareFallback(url);setShareMessage('Copy this view link');}};
 const launches=useMemo(()=>atlas?partLaunchTimes(atlas):new Float64Array(),[atlas]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const start=useMemo(()=>atlas?timelineStart(atlas):TIMELINE_END,[atlas]),timelineDays=Math.round((TIMELINE_END-start)/DAY_MS),assembling=state.assembly!==null;
 const arrival=useMemo(()=>atlas&&state.assembly!==null?latestArrival(atlas,state.assembly):undefined,[atlas,state.assembly]);
 // Play advances one year every two seconds and stops on the complete station (assembly null).
 useEffect(()=>{if(!playing)return;let frame=0,last=performance.now(),at=assemblyRef.current??start;const tick=(now:number)=>{const next=advanceAssembly(at,Math.min(now-last,100));last=now;setState(s=>({...s,assembly:next}));if(next===null){setPlaying(false);return;}at=next;frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,start]);
 const togglePlay=()=>{if(playing){setPlaying(false);return;}setState(s=>({...s,assembly:s.assembly??start,explode:0,isolate:false}));setPlaying(true);};
 const scrub=(day:number)=>{setPlaying(false);setState(s=>day>timelineDays?{...s,assembly:null}:{...s,assembly:start+day*DAY_MS,explode:0,isolate:false});};
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const isVisible=visibilityFor(state),visibleCount=atlas?.parts.filter((p,i)=>isVisible(p,launches[i])).length??0;
 const futureLaunch=atlas&&state.assembly!==null?Math.max(-Infinity,...atlas.parts.flatMap((p,i)=>state.selected.includes(p.id)&&launches[i]>state.assembly! ? [launches[i]]:[])):-Infinity;
 const hasFutureSelection=Number.isFinite(futureLaunch);
 const jumpToSelection=()=>{setPlaying(false);setState(s=>({...s,assembly:futureLaunch>TIMELINE_END?null:futureLaunch,reset:s.reset+1}));};
 const citations=useMemo(()=>{const links=new Map<string,string[]>();for(const [fact,urls] of Object.entries(SOURCES[chosen?.id??'']??{}))for(const url of [urls].flat()){if(!url)continue;links.set(url,[...(links.get(url)??[]),fact]);}return [...links].map(([url,facts])=>({url,label:facts.join(', ')}));},[chosen?.id]);
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return SUGGESTED.map(id=>atlas.concepts.find(c=>c.id===id)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setPlaying(false);setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setPlaying(false);setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<SceneBoundary onError={setError}><Suspense fallback={null}><StationScene theme={theme} atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/></Suspense></SceneBoundary>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> INTERACTIVE STATION MODEL</div><h1>Station Atlas<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'382'} modeled pieces <span>·</span> NASA ISS complete 2011</div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search the station"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button theme-toggle" aria-label={theme==='light'?'Switch to dark mode':'Switch to light mode'} title={theme==='light'?'Switch to dark mode':'Switch to light mode'} onClick={()=>setTheme(t=>t==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</Button><Button variant="ghost" className="icon-button" aria-label="About this model" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Station systems">
   <div className="panel-heading"><span>Systems</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close systems"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>All</Button>{PRESETS.map(p=><Button variant="ghost" key={p.name} aria-pressed={state.visible.length===p.systems.length&&p.systems.every(id=>state.visible.includes(id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:p.systems}))}>{p.name}</Button>)}</div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name.toLowerCase()}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find a structure"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Destiny, Canadarm2, solar array…" aria-label="Search named station structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major module, or search every named structure.'}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate station'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'SELECTED STRUCTURE'):arrival?`${arrival.launch?.flight} · ${arrival.name}`.toUpperCase():state.explode>.95?'STATION INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':'COMPLETE REFERENCE MODEL'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open system layers"><Layers3 size={20}/><span>Systems</span></Button><div className="timeline-control"><Button variant="ghost" className="timeline-play" onClick={togglePlay} aria-label={playing?'Pause assembly':'Play assembly'} title={playing?'Pause assembly':'Play assembly'}>{playing?<Pause size={16}/>:<Play size={16}/>}</Button><div className="explode-control"><div className="explode-label"><label id="assembly-label">Assembly</label><output title={state.assembly===null?"Complete reference model, including elements launched after 2011":new Date(state.assembly).toISOString().slice(0,10)}>{state.assembly===null?"Complete":new Date(state.assembly).getUTCFullYear()}</output></div><Slider getAriaValueText={(_,day)=>day>timelineDays?'Complete reference model':new Date(start+day*DAY_MS).toISOString().slice(0,10)} aria-labelledby="assembly-label" min={0} max={timelineDays+1} step={1} value={[state.assembly===null?timelineDays+1:(state.assembly-start)/DAY_MS]} onValueChange={v=>scrub(Array.isArray(v)?v[0]:v)}/><div className="slider-endpoints"><span>{new Date(start).getUTCFullYear()}</span><span>2011 · Complete</span></div></div></div><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode station</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" disabled={assembling} min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect</span><div className="footer-actions"><Button variant="ghost" onClick={share}>Copy view link</Button><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></div></footer>
  {shareMessage&&<div className="share-feedback glass" role="status"><span>{shareMessage}</span>{shareFallback&&<input aria-label="View link" readOnly value={shareFallback} onFocus={e=>e.target.select()}/>}<Button variant="ghost" aria-label="Dismiss share message" onClick={()=>{setShareMessage('');setShareFallback('');}}><X size={16}/></Button></div>}
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the station</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'382'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'STATION'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}>{hasFutureSelection&&<div className="future-selection"><p>{state.selected.length===1?"This piece is":"Some selected pieces are"} hidden at this assembly date. {futureLaunch>TIMELINE_END?"They launched after the historical timeline ends in 2011.":`All selected pieces are available from ${new Date(futureLaunch).toISOString().slice(0,10)}.`}</p></div>}<SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.id,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.id]&&<span className="context-note">System overview · structure identified from the source model</span>}<div className="structure-meta"><span>Atlas reference<strong>{chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<div className="structure-sources"><h3>Sources for these facts</h3>{citations.length?citations.map(c=><a key={c.url} className="source-link" href={c.url} target="_blank" rel="noreferrer">{c.label} <ArrowUpRight size={14}/></a>):<a className="source-link" href="https://www.nasa.gov/international-space-station/" target="_blank" rel="noreferrer">Station overview <ArrowUpRight size={14}/></a>}</div></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} disabled={assembling&&!hasFutureSelection} onClick={()=>hasFutureSelection?jumpToSelection():setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{hasFutureSelection?(futureLaunch>TIMELINE_END?'Show complete reference model':'Jump to launch'):state.isolate?'Show surrounding station':'Isolate structure'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">A station, unfolded.</SheetTitle><SheetDescription>Explore the International Space Station in its projected 2011 configuration.</SheetDescription><div className="about-copy"><p><strong>NASA · ISS complete 2011</strong><br/>382 individually selectable pieces built from the 73 object layers of NASA Johnson’s Lightwave reference model.</p><p>This model reflects assembly as planned for 2011. It predates Prichal, the Bishop airlock, the roll-out solar arrays, Axiom modules, and Nauka’s final position, and it carries no visiting vehicles. Names and concepts group pieces by flight element; each source mesh is rendered once.</p><p>The assembly timeline adds each element on its launch date from NASA’s assembly sequence, shown at its 2011 position. Nauka and the European Robotic Arm launched in 2021, so they arrive only when the timeline reaches the complete model.</p><p>Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations give sourced launch facts for each element. This is an educational model, not an engineering reference.</p><h3>Source</h3><p>International Space Station model, NASA Johnson Space Center Visual Communications Lab, February 2011. Public domain; courtesy NASA.</p><a href="https://science.nasa.gov/3d-resources/international-space-station-iss-c-high-res/" target="_blank" rel="noreferrer">Source model <ArrowUpRight size={14}/></a><a href="/ATTRIBUTION.md" target="_blank" rel="noreferrer">Full attribution <ArrowUpRight size={14}/></a><a href="https://www.nasa.gov/international-space-station/" target="_blank" rel="noreferrer">NASA station overview <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
