"""Write EXPLANATIONS and SOURCES in app/anatomy.ts from docs/station-facts.json.
Usage: python scripts/build-explanations.py
Each fact in the JSON is [value, url, ...more urls]; a null fact is left out of the text and the source map.
validate-atlas.mjs checks that every part's concept has an explanation and every stated fact cites a nasa.gov or esa.int page.
"""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
facts=json.loads((root/'docs/station-facts.json').read_text(encoding='utf8'))['facts']
KEYS=['launch','vehicle','agency','mass','purpose']
explanations={};sources={}
for cid,f in facts.items():
 get=lambda k:f.get(k)[0] if f.get(k) else None
 purpose,launch,vehicle,agency,mass=get('purpose'),get('launch'),get('vehicle'),get('agency'),get('mass')
 assert purpose,f'{cid}: a purpose is required'
 text=[purpose.rstrip('.')+'.']
 if launch or vehicle:text.append('Launched'+(f' {launch}' if launch else '')+(f' aboard {vehicle}' if vehicle else '')+'.')
 if agency:text.append('Provided by '+agency.removeprefix('Provided by ').rstrip('.')+'.')
 if mass:text.append(f'Mass {mass}.')
 explanations[cid]=' '.join(text)
 sources[cid]={k:(f[k][1] if len(f[k])==2 else f[k][1:]) for k in KEYS if f.get(k)}
block=('/** Keyed by concept id. Generated by scripts/build-explanations.py from docs/station-facts.json; edit the JSON, not this block. */\n'
 'export const EXPLANATIONS:Record<string,string> = {\n'+''.join(f' {json.dumps(k)}:{json.dumps(v,ensure_ascii=False)},\n' for k,v in explanations.items())+'};\n'
 '/** The nasa.gov or esa.int page behind each fact stated in EXPLANATIONS. */\n'
 "export const SOURCES:Record<string,Partial<Record<'launch'|'vehicle'|'agency'|'mass'|'purpose',string|string[]>>> = {\n"+''.join(f' {json.dumps(k)}:{json.dumps(v,ensure_ascii=False,separators=(",",":"))},\n' for k,v in sources.items())+'};\n')
p=root/'app/anatomy.ts';s=p.read_text(encoding='utf8')
a=s.index('/** Keyed by concept id.');b=s.index('export function explanation')
p.write_text(s[:a]+block+s[b:],encoding='utf8')
print(f'{len(explanations)} explanations written; facts left unsourced: {sum(1 for f in facts.values() for k in KEYS if not f.get(k))}')
