// Publish a staged conversion with content-addressed chunks, then replace the manifest last.
// Usage: node scripts/publish-model.mjs work/restored
import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {gzipSync} from 'node:zlib';
const from=path.resolve(process.argv[2]??'work/restored'),to=path.resolve('public/models');
const atlas=JSON.parse(fs.readFileSync(path.join(from,'atlas.json')));
const existing=JSON.parse(fs.readFileSync(path.join(to,'atlas.json')));
for(const c of atlas.concepts){const old=existing.concepts.find(x=>x.id===c.id);if(old?.launch)c.launch=old.launch;}
for(const p of atlas.parts){const old=existing.parts.find(x=>x.id===p.id);if(old?.launchDate)p.launchDate=old.launchDate;}
for(const c of atlas.chunks){
 const data=fs.readFileSync(path.join(from,path.basename(c.url))),hash=createHash('sha256').update(data).digest('hex').slice(0,16);
 c.url=`/models/station-${hash}.bin`;c.gzip=c.url+'.gz';const compressed=gzipSync(data,{level:9});c.gzipBytes=compressed.length;
 fs.writeFileSync(path.join(to,path.basename(c.url)),data);fs.writeFileSync(path.join(to,path.basename(c.gzip)),compressed);
}
fs.cpSync(path.join(from,'textures'),path.join(to,'textures'),{recursive:true});
fs.writeFileSync(path.join(to,'atlas.json'),JSON.stringify(atlas));
// Remove only superseded files generated by this converter or its former optimizer.
const live=new Set(atlas.chunks.flatMap(c=>[path.basename(c.url),path.basename(c.gzip)]));
for(const filename of fs.readdirSync(to))if(/^(?:body-\d+|station-(?:\d+|[a-f0-9]{16}))\.bin(?:\.gz)?$/.test(filename)&&!live.has(filename)){
 const target=path.resolve(to,filename);if(path.dirname(target)!==to)throw new Error('Unexpected output path');fs.unlinkSync(target);
}
console.log(JSON.stringify({triangles:atlas.triangles,materials:atlas.materials.length,textureFiles:fs.readdirSync(path.join(from,'textures')).length,geometryDownloadMB:atlas.chunks.reduce((n,c)=>n+c.gzipBytes,0)/1e6,unsupported:atlas.appearance.unsupportedEffects},null,2));
